# NUMPY
## Numerical Python

In [1]:
import numpy as np

In [2]:
a1 = np.array([2,3,4,5,6])
a1

array([2, 3, 4, 5, 6])

In [9]:
a1.ndim # no. of dimenstions

1

In [10]:
a1.size # no. of elements

5

In [11]:
a1.shape

(5,)

In [13]:
a2 = np.array([
    [2,4],[5,6],[8,9]
])
a2

array([[2, 4],
       [5, 6],
       [8, 9]])

In [14]:
a2.ndim

2

In [15]:
a2.size

6

In [17]:
a2.mean()

np.float64(5.666666666666667)

# Dimensions

In [21]:
a4 = np.array([[[1,2,3,4]]])
a4

array([[[1, 2, 3, 4]]])

In [23]:
a4.ndim

3

In [25]:
a4.shape

(1, 1, 4)

In [28]:
a4.flatten()

array([1, 2, 3, 4])

In [31]:
np.ravel(a4) # more scalable

array([1, 2, 3, 4])

# Different Ways of creating array

In [32]:
a5 = np.arange(20)
a5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
a6 = np.arange(22,33,2) # start , end , updation
a6

array([22, 24, 26, 28, 30, 32])

In [36]:
a7 = np.ones((3,4))
a7

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
a8 = np.zeros((3,4))
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
a9 = np.identity(3) # identity matrix
a9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
a10 =np.random.random((2,3))
a10

array([[0.9796096 , 0.01342196, 0.70314326],
       [0.55427361, 0.98713201, 0.18752803]])

In [67]:
a11 =np.random.randint(0,50,3)
a11

array([17, 40, 25], dtype=int32)

In [48]:
np.random.randint(1, 10, size=(3, 3))

array([[9, 4, 7],
       [5, 6, 6],
       [2, 1, 9]], dtype=int32)

In [52]:
np.random.permutation([1, 2, 3, 4])

array([4, 2, 1, 3])

In [57]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
arr

array([3, 1, 4, 2, 5])

In [59]:
np.random.randn(3)

array([ 2.3520919 , -1.81504825, -0.59139621])

In [64]:
np.random.rand(2,3)

array([[0.55354913, 0.0889021 , 0.52937893],
       [0.13174177, 0.23323834, 0.54241996]])

# Matrix operations

### multiplication

In [74]:
a = np.array([[2,4],[6,7]])
b = np.array([[3,6],[6,8]])


In [76]:
result = np.matmul(a,b)

In [77]:
result

array([[30, 44],
       [60, 92]])

In [78]:
add = a + b
add

array([[ 5, 10],
       [12, 15]])

In [79]:
a - b

array([[-1, -2],
       [ 0, -1]])

In [83]:
np.matrix_transpose(a)

array([[2, 6],
       [4, 7]])

In [88]:
b / 2

array([[1.5, 3. ],
       [3. , 4. ]])

# Indexing and slicing

In [90]:
arr = np.arange(12,24,2)

In [91]:
arr

array([12, 14, 16, 18, 20, 22])

In [92]:
arr[1]

np.int64(14)

In [94]:
arr[1:3]

array([14, 16])

In [98]:
arr[2:-1]

array([16, 18, 20])

In [99]:
arr[:-1]

array([12, 14, 16, 18, 20])

In [102]:
arr2 = np.arange(0,24).reshape(6,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [105]:
arr2[1:4 , 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [106]:
arr2[3:6 , :-1]

array([[12, 13, 14],
       [16, 17, 18],
       [20, 21, 22]])

In [114]:
np.array([arr2[0,3],arr2[1,2],arr2[2,1],arr2[3,3]])

array([ 3,  6,  9, 15])

In [117]:
arr2[2:-1 , -2:]

array([[10, 11],
       [14, 15],
       [18, 19]])

In [128]:
arr2[:,::2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22]])

In [133]:
arr2[::2,:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [134]:
arr3 = np.arange(36).reshape(6,6)
arr3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [144]:
arr3[1:4:2 , 1:4:2]

array([[ 7,  9],
       [19, 21]])

In [167]:
arr3[1:4:2,-3::-2]

array([[ 9,  7],
       [21, 19]])

In [177]:
arr4 = np.random.randint(10,50,(3,3))
arr4

array([[23, 16, 16],
       [30, 43, 40],
       [18, 26, 35]], dtype=int32)

In [180]:
np.argmax(arr4,axis=1) # row wise max element index

array([0, 1, 2])

In [179]:
np.argmax(arr4,axis=0) # col wise max element index

array([1, 1, 1])

In [181]:
np.argmin(arr4,axis=1) # row wise min element index

array([1, 0, 0])

In [182]:
np.argmin(arr4,axis=0) # col wise min element index

array([2, 0, 0])

In [185]:
np.linspace(10,100,5)  # 5 evenly spaced numbers between 10 and 100

array([ 10. ,  32.5,  55. ,  77.5, 100. ])